instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: nginx
    release: nginx
  name: nginx
  networks:
  - name: default
  stemcell: default
  vm_type: small
name: byllc-nginx
release:
  name: byllc-nginx
releases:
- name: nginx
  version: latest
stemcells:
- alias: default
  os: ubuntu-trusty
  version: 3586.16
update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 10
  update_watch_time: 1000-30000
